substitutions:
  build_type: release
  ssid: ssid

external_components:
  - source: components
    components: [stairs_light]

esphome:
  name: steps  
  platformio_options: 
    build_type: $build_type

esp32:
  board: upesy_wroom 

# api:

# wifi:
#   ssid: Wokwi-GUEST

logger: 
  level: DEBUG
  
binary_sensor:
  - platform: gpio
    id: pir1
    pin: 5
    internal: True
    on_press: 
      then:
        - stairs_light.run:
            id: mysteps
            reversed: true
            animation: arrow
        - wait_until: 
            condition:
              lambda: return !id(mysteps).is_running();
        - logger.log: animation completed
        # - stairs_light.step_on:
        #     id: mysteps
        #     step: 3
        #     red: 100%
        #     transition_length: 1000ms
        - delay: 3s
        - light.turn_off: line

  - platform: gpio
    id: pir2
    pin: 4  
    internal: True
    on_press:
      then:
        - stairs_light.run:
            id: mysteps
            animation: arrow
        - wait_until: 
            condition:
              lambda: return !id(mysteps).is_running();
        - logger.log: animation completed
        - delay: 3s
        - light.turn_off: line
              
              
light:  
  - id: line
    name: Цвет
    platform: esp32_rmt_led_strip
    chipset: WS2812
    num_leds: 172
    pin: 18
    rgb_order: GRB
    rmt_channel: 0
    default_transition_length: 
      milliseconds: 10
    internal: True        

# Настройки компонента steps
stairs_light:
  id: mysteps
  led: line
  steps: [21,-21,21,-23,23,-21,21,-21]
  animations:
    - fade:
    - arrow:
        increment: 3
  animation_length: 4000ms  
