substitutions:
  build_type: release
  ssid: ssid

external_components:
  - source: components
    components: [stairs_light]

esphome:
  name: steps  
  platformio_options: 
    build_type: $build_type

esp32:
  board: upesy_wroom 

api:

wifi:
  ssid: Wokwi-GUEST

logger: 
  level: DEBUG

switch:
  - id: moveSensorsEnabled
    platform: template
    name: 'Включать по датчикам'
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True
  - id: stair_entry_light
    platform: template
    name: 'Подсвечивать первые ступени'
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True
    on_turn_on: 
      then:
        - lambda: |-
            id(mysteps)->set_entry_light(.5f);
    on_turn_off: 
      then:
        - lambda: |-
            id(mysteps)->set_entry_light(0.f);
  
binary_sensor:
  - platform: gpio
    id: pir1
    pin: 5
    internal: True
    on_press: 
      then:
        - script.execute: 
            id: stairs_light_animation
            direction: DOWN

  - platform: gpio
    id: pir2
    pin: 4  
    internal: True
    on_press:
      then:
        - switch.toggle: moveSensorsEnabled
        # - script.execute: 
        #     id: stairs_light_animation
        #     direction: UP
              
              
light:  
  - id: line
    name: Цвет
    platform: esp32_rmt_led_strip
    chipset: WS2812
    num_leds: 172
    pin: 18
    rgb_order: GRB
    rmt_channel: 0
    default_transition_length: 
      milliseconds: 10
    internal: True        

# Настройки компонента steps
stairs_light:
  id: mysteps
  led: line
  steps: [21,-21,21,-23,23,-21,21,-21]
  animations:
    - fade:
    - arrow:
        increment: 3
  animation_length: 4000ms  

script:
- id: stairs_light_animation
  mode: single
  parameters: 
    direction: string
  then: 
  - if: 
      condition:
        switch.is_on: moveSensorsEnabled
      then:
      - logger.log: 
          level: DEBUG
          format: "Запуск анимации в направлении: %s"
          args: [ 'direction.c_str()' ]
          
      - stairs_light.turn_on:
          id: mysteps
          # Лямбда проверяет направление
          reversed: !lambda |-
            return direction == "DOWN";
            
      - wait_until: 
          condition:
            lambda: return !id(mysteps).is_running();
            
      - logger.log: 
          level: DEBUG
          format: "animation completed"
      - delay: 3s
      - stairs_light.turn_off: 
          id: mysteps
          transition_length: 1500ms


button:
  - platform: template
    name: "Stairs Down"
    on_press:
      - script.execute:
          id: stairs_light_animation
          direction: "DOWN"
          
  - platform: template
    name: "Stairs Up"
    on_press:
      - script.execute:
          id: stairs_light_animation
          direction: "UP"
  - platform: template
    name: Restart
    on_press: 
      - lambda: "ESP.restart();"
          
        
